### ISSUE TITLE
Error in Angular Simple-Todos tutorial docs

### ISSUE THREAD

**Issue by jeremybrenner** [meteor/simple-todos-angular#1]
I think there may be an error with this code in the Angular-Meteor tutorial on Meteor.com. When you you come to the part of the tutorial that has you rebuild the template, the code reads:

```
<!-- replace the existing task template with this code -->
<li ng-class="{'checked': task.checked}">
  <button class="delete" ng-click="tasks.remove(task)">&times;</button>

  <input type="checkbox" ng-model="task.checked" class="toggle-checked" />

  <span class="text"></span>
</li>
```

So if the code is copied exactly you won't be templating any values into the span, and the app breaks!

**Comment by Urigo** [comment]
@jeremybrenner thanks for noticing!
I've pushed a fix and the new version will be deployed soon.
In the meantime you can have a look on the code diff to help you solve to missing piece:
https://github.com/meteor/simple-todos-angular/commit/2c5420e51ca2d0177d83befad0730adea8e75c4a

**Comment by jeremybrenner** [comment]
Any time @Urigo! Thanks!
