### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by alextaaa** [meteor/simple-todos-angular#10]
Problem in file https://github.com/meteor/simple-todos-angular/blob/master/simple-todos-angular.html
`Uncaught SyntaxError: missing ) after argument list`

`<body ng-include="'todos-list.ng.html'" ...`

**Comment by Gargamil** [comment]
can confirm this.

**Comment by alextaaa** [comment]
http://i.imgur.com/FosBEB7.jpg

**Comment by YC00** [comment]
change the line:5 from ng-include="'todos-list.ng.html'" to ng-include='"todos-list.ng.html"' in file simple-todos-angular.html will solve the problem

**Comment by stubailo** [comment]
There's now an issue tracking this on Meteor: https://github.com/meteor/meteor/issues/5276

**Comment by Urigo** [comment]
Fixed in the new Meteor 1.2.0.2.
Just run `meteor update` in the command line
