### ISSUE TITLE
From Example

### ISSUE THREAD

**Issue by datnordstrom** [meteor/simple-todos-angular#11]
Remove from example in step 2:
ng-app="simple-todos"

Otherwise error will appear in console:
WARNING: Tried to load angular more than once.

**Comment by Urigo** [comment]
@datnordstrom are you sure?  that seem strange and working for me.
Can you please provide a reproduction?

**Comment by Urigo** [comment]
@datnordstrom Meteor 1.2.0.2 is out and also the new tutorial version.
Please test again and reopen if it happens to you again
