### ISSUE TITLE
Users interface

### ISSUE THREAD

**Issue by alextaaa** [meteor/simple-todos-angular#12]
I do not see the user interface
http://i.imgur.com/O5geN6J.jpg

**Comment by Urigo** [comment]
@alextaaa have you changed `meteor-include` to `blaze-template` ?
http://angular-meteor.com/api/blaze-template

**Comment by alextaaa** [comment]
I tried to use your package, but the problem remains
http://i.imgur.com/n0kv9wq.jpg

**Comment by Urigo** [comment]
can you please share al of your code?  thanks

**Comment by alextaaa** [comment]
I have not changed anything in the source code of the application
I tried to run a test example angular
but if it helps resolve an issue, here's the code
https://github.com/alextaaa/simple-todos-angular

**Comment by Urigo** [comment]
@alextaaa you haven't updated the HTML.
I've created a pull request for your repo with a fix: https://github.com/alextaaa/simple-todos-angular/pull/1

**Comment by alextaaa** [comment]
Thanks for the quick fix bugs
Can I become a member of Meteor Development Group ?

**Comment by Urigo** [comment]
@alextaaa you can contact us through https://www.meteor.com/jobs and choose the role you think will be best fit for you
