### ISSUE TITLE
ReferenceError: Template is not defined

### ISSUE THREAD

**Issue by luisRojas29** [meteor/simple-todos-angular#14]
Hello there, while following the tutorial, in step 9 after include the blaze template, this is not rendered in the browser, so inspecting I found that _ReferenceError: Template is not defined_ with the blaze template, what am I missing??

**Comment by wahyutp** [comment]
Same problem here. I just clone the whole project example and meteor run it , it gives me the same error. Maybe because of meteor 1.2.1 update and removing the blaze-html-templates package

**Comment by Urigo** [comment]
I'm on it, will be solved and updated in a couple of minutes

**Comment by Urigo** [comment]
Fixed, check out the updated chapter - https://www.meteor.com/tutorials/angular/adding-user-accounts
