### ISSUE TITLE
Attempting to add user accounts (Step 9)

### ISSUE THREAD

**Issue by arodr967** [meteor/simple-todos-angular#15]
Every time I use the command:
`meteor add accounts-password dotansimha:accounts-ui-angular` as provided in the tutorial, I get the following response:

![step9](https://cloud.githubusercontent.com/assets/11788477/12037805/52d19644-ae20-11e5-97fd-2e0dc5d6d462.PNG)

I tried to do the environment variables but I don't think I'm using Meteor behind a proxy... I am using Windows 7.

**Comment by Urigo** [comment]
@arodr967 are you sure your internet connection works fine?

**Comment by arodr967** [comment]
I was connected to an Ethernet cable. I now used my WiFi and it worked!
