### ISSUE TITLE
erreur tutorial meteor/angular simple-todos-angular.js

### ISSUE THREAD

**Issue by francis-barban** [meteor/simple-todos-angular#6]
line 54 :         return Tasks.find({ checked: {$ne: true} }).count();
replace by :        return Tasks.find({},{ checked: {$ne: true} }).count();

**Comment by Urigo** [comment]
@francis-barban why?  the first parameter is `find` is the `query` parameter and that's what we are using..

**Comment by Urigo** [comment]
Closing for now
