### ISSUE TITLE
bugs after update to meteor 1.2.0.1

### ISSUE THREAD

**Issue by h4de5** [meteor/simple-todos-angular#9]
some packages seems to have been moved around. to make the angular example app work again try this:

if the login buttons do not show up install the blaze-template package

``` bash
meteor add urigo:angular-blaze-template
```

and change the template call in todos-list.ng.html from:

``` html
<meteor-include src="loginButtons"></meteor-include>
```

to

``` html
<blaze-template name="loginButtons"></blaze-template>
```

in case you get the following error in the console:

> ReferenceError: EJSON is not defined

you may need to add the EJSON package:

``` bash
meteor add ejson
```

this will also fix the problem, when switching between private/public states of one item will add the same item over and over again in different opened sessions.

it also seems the current urigo:angular package does not work with meteor. therefor i updated it to the latest version:

```
meteor add urigo:angular@0.10.2
```

just to find out, that this package is marked as deprecated. so i removed it and added the suggested one:

```
meteor remove urigo:angular
meteor add angular
```

also when creating an android app i was asked to install git - not sure if this was necessary before:
`sudo zypper install git-core`

hope that helps some meteor noobs like me..

**Comment by fxckdead** [comment]
@h4de5 this should be in the main repo too ^^ thx for the `urigo:angular-blaze-template`thing :+1:

**Comment by Urigo** [comment]
Updated the tutorial, will be deployed to meteor.com soon

**Comment by fxckdead** [comment]
@Urigo what about the `meteor-include`? it's a kind of bug or what?

**Comment by Urigo** [comment]
No, it's just an old API.
It was deprecated in favor of blaze-template - http://angular-meteor.com/api/blaze-template
The actual code looks like this: https://github.com/meteor/simple-todos-angular/commit/e9c7eaa065b5046a7ec4f9d138911ecfd486a18f

**Comment by Urigo** [comment]
Meteor 1.2.0.2 is out and the tutorial has been updated.
Thank you all so much for the valuable feedback!
